### ISSUE TITLE
A promising tool, but I can't get it to work.

### ISSUE THREAD

**Issue by WolfgangDpunkt** [hauke96/wiki2book#14]
Help would be great. :-) Thank you very much!
I'm testing it on Raspberry Pi OS (64-bit).

In the directory `~/wiki2book/src` I enter `./wiki2book article Erde`.

And then this error message follows, which is incomprehensible to me:

```
2022-11-07 14:25:59.173 [FATAL] main.go:56 | Unknown command: article <article-name>
&kong.Context{Kong:(*kong.Kong)(0x40001207e0), Path:[]*kong.Path{(*kong.Path)(0x4000100d20), (*kong.Path)(0x4000100d70), (*kong.Path)(0x4000100dc0)}, Args:[]string{"article", "Erde"}, Error:error(nil), values:map[*kong.Value]reflect.Value{(*kong.Value)(0x400011f5f0):reflect.Value{typ:(*reflect.rtype)(0x2f68e0), ptr:(unsafe.Pointer)(0x40001136b0), flag:0x198}}, bindings:kong.bindings{}, resolvers:[]kong.Resolver(nil), scan:(*kong.Scanner)(0x400011c300)}
```

Putting the word **Erde** in inverted commas and the like doesn't help.

I have successfully installed the following components:
- ImageMagick
- Pandoc
- DejaVu fonts 
- go

And then built the project successfully with `go build -o wiki2book .`
I have also rebooted.

If helpful, here are some more details:
I have tried running tests.sh:

```
Finished 
all integration-tests after 53448 milliseconds

These integration-tests FAILED:
    real-article-Erde
    real-article-Schwarzes_Loch
    real-article-Schwarzes_Loch
    real-article-Sonne

```
One log file: [real-article-Erde.log](https://github.com/hauke96/wiki2book/files/9952048/real-article-Erde.log) 

Apparently something is wrong with the image conversion? 
But the `convert` command is available and works (Version: ImageMagick 6.9.11-60 Q16 aarch64 2021-01-25)

**Comment by WolfgangDpunkt** [comment]
Dear Hauke,

thank you very much for your super-fast and friendly answer.

Seems like I was a bit too early as an early adopter.
But I am very much looking forward to trying out new features of your tool.

Currently there is no really satisfactory self-hosting solution for the task of converting Wikipedi articles into ebooks, I assume that is also your motivation for developing a new tool.
I've been researching solutions to this for a while and perhaps it might be helpful if I share my findings here:

wb2pdf/mediawiki2latex
https://de.wikibooks.org/wiki/Benutzer:Dirk_H%C3%BCnniger/wb2pdf
The former official epub tool of Wikipedia, now available as an outsourced tool. It works quite well, though it ignores some of the images during creation and is a bit slow and clunky.

https://epub.press/
https://github.com/haroldtreen/epub-press
The self-hosted backend works well, also it seemed to capture all images when converting, but handling it as a self-hosted variant is cumbersome and has many dependencies that don't run on arm64 devices. There is also a limitation on the number of pages, images and image quality.

W2EB
https://github.com/Dave-Gilbert/w2eb
Very interesting tool that also focuses on the structural optimisation of content for ebook readers (e.g. the integration of sub-page summaries as footnotes). Unfortunately, it seems to have been abandoned 3 years ago. I couldn't get it to work because of numerous problems, it is still written for Python 2.7.

Percollate
https://github.com/danburzo/percollate
"Percollate is a command-line tool that turns web pages into beautifully formatted PDF, EPUB, or HTML files." And it generally does this very well and fast. Unfortunately, also with this application, images get lost on Wikipedia pages, no matter which source format is used.

**Comment by hauke96** [comment]
Thanks for sharing. I also found the first three tools before I started my own project. Percollate is new to me but also produces rather bad results: Images are missing, videos are included instead (what?!) and the text contains a lot of stuff that should not be part of a real book (at least not in my opinion). But interesting that such a general purpose tool creates at least well formatted and styled results.

Anyway, my ambition is to render Wikipedia articles at least as fancy as ebooks from a book store.

**Comment by hauke96** [comment]
I just uploaded some smaller changes regarding logging. When the `convert` command fails, the stderr-output will be printed as well. Maybe this gives us some insight into the failing convert-command on your machine (because everything works on my machines). Please try it again and upload the log file, thanks :)

**Comment by WolfgangDpunkt** [comment]
"Wikipedia articles at least as fancy as ebooks from a book store."
That is a very glorious goal!
In fact, all previous solutions always have some kind of disadvantage, they fail at the latest at tables (which in many wiki articles contains relevant standardised overview information at the beginning of the article) or at the footnotes. Images are also difficult, as I mentioned.

I'll be happy to try out the new version right away.
I have already kind of achieved my goal of setting up a self-hosted read-it-later service quite well, with the Percollate tool I mentioned (for example for spiegel.de or zeit.de), in combination with a iOS shortcut and my small home server.
But since a lot of the articles I want to read later originate from from Wikipedia, your work here is very gratifying for me. Thanks a lot!

**Comment by WolfgangDpunkt** [comment]
I downloaded the new version, built it and tried it out. It doesn't work yet, but at least it gives different error messages: ;-)
`./wiki2book article Erde -d`
leads to:
`./wiki2book article "[ERROR] main.go:150 | chdir .wiki2book: no such file or directory"`

Running tests.sh shows this result: 
```
These integration-tests FAILED:
    real-article-Erde
    real-article-Sonne
```
In the log, there are these three lines that contain ERROR:
```
2022-11-13 17:33:52.908 [ERROR] api.go:128   | Converting image results/test-real-article-Sonne/images/Highest_resolution_photo_of_Sun_(NSF)_as_of_January_20,_2020.jpg failed
2022-11-13 17:33:52.910 [ERROR] main.go:116  | exit status 1
convert-im6.q16: cache resources exhausted `results/test-real-article-Sonne/images/Highest_resolution_photo_of_Sun_(NSF)_as_of_January_20,_2020.jpg' @ error/cache.c/OpenPixelCache/4095.

```

**Comment by hauke96** [comment]
### Missing `.wiki2book` folder

When using `wiki2book article ...` there must be a `.wiki2book` folder that contains cached files. In the meantime I pushed several things including a commit that will create such a folder when its missing.

### Regarding the integration tests

Looks like a ImageMagick problem on your side. I googled the error message and found this: https://stackoverflow.com/questions/31407010/cache-resources-exhausted-imagemagick Maybe adjusting the `policy.xml` helps?

**Comment by WolfgangDpunkt** [comment]
Very nice, a breakthrough. At least on my system. 
`./wiki2book article Hamburg`
Creating ebooks via "article" works very well. The result already looks pretty good! Thank you very much for your efforts.

For the sake of completeness, I started tests.sh again, with the same result as described above. 
So still the same error, which I will now look into with the help of your link.

**Comment by hauke96** [comment]
Nice! :D

Please let me know if and how you fixed the ImageMagick issue. I leave issue open until then.

**Comment by WolfgangDpunkt** [comment]
Thank you very much, I have now tested it extensively and the ImageMagick problem was solved with the linked solution, i.e. increasing the limits for memory and co.
I have a lot of fun with wiki2book! This is really the very best solution for Wikipedia-Epubs at the moment.
Even though I have noticed a new problem. But that's another story
